vulgo = str(input('Digite seu nome completo: ')).strip()
V = vulgo.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(V[0]))
print('Seu último nome é {}'.format(V[-1]))
print('_' * 8)
"""fra = str(input('Digite uma frase: ')).strip().upper()
# F = fra.upper()
print('A letra "A" aparece {} vezes na sua frase'.format(fra.count('A')))
print('A primeira letra "A" aparece na posição {}'.format(fra.find('A') + 1))
print('A última letra "A" apareceu na posição {}'.format(fra.rfind('A') + 1))
print('_' * 8)
nom = str(input('Qual é seu nome completo? ')).strip()
no = nom.title()
print('Seu nome tem Silva ? {}'.format('Silva' in no))
print('_' * 8)
cidade = str(input('Em que cidade você nasceu? ')).strip()
# print(cidade[:5].upper() == 'Santo')
cid = cidade.capitalize()
print('Santo' in cid) 
print('_' * 8)
number = int(input('Informe um número: '))
u = number // 1 % 10
d = number // 10 % 10
c = number // 100 % 10
m = number // 1000 % 10
print(f'Analisando o número {number}')
print('unidade: {}'.format(u))
print('Dezena: {}'.format(d))
print('Centena: {}'.format(c))
print('Milhar: {}'.format(m))
print('_' * 8)
name = input('Digite seu nome completo: ').strip()
print('Analisando seu nome...')
po = name.split()
print('Seu nome em maiúsculas é', name.upper())
print('Seu nome em munúsculas é', name.lower())
print('Seu nome tem ao todo {}'.format(len(name)-name.count(' ')))
print('Seu primeiro nome é {} e ele tem {} letras'.format(po[0], len(po[0])))"""
print('_' * 8)
frase = 'Negócio legal de se estudar'
f2 = '  Olha a frase  '
print(frase)
# print("""lalaallalalllalalllallalllalalallallalllaallalallkkskskskksk""") ele escreve de maneira mais eficaz
# print(frase[9:4])
print(len(frase))
print(frase.count('es'))
print(frase.count('es', 0, 6))
print(frase.find('estudar'))
print(frase.find('bolsonaro'))  # não existe = -1
print('legal' in frase)
print(frase.replace('A', 'O'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())  # deixa a primeira letra maiúscula
print(frase.title())
print(frase.lower().find('Negócio'))
pi = frase.split()
print(pi[1])  # [3]
print('_' * 8)
print(f2)
print(f2.strip())
print(f2.rstrip())
print(f2.lstrip())
print(f2.split())
print('-'.join(f2))
